name: 'Test'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/test-npm.yml@v1
    with:
      installCommand: 'ci --include=dev --omit=optional'
      buildCommand: 'build-prod'
      nodeVersionMatrix: '[ "18.x", "24.x" ]'
